configDependencies:
  '@pnpm/plugin-trusted-deps': latest

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@azat-io/*'

onlyBuiltDependenciesFile: node_modules/.pnpm-config/@pnpm/plugin-trusted-deps/allow.json
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  netlify-cli: true
  sharp: true
  simple-git-hooks: true
  unix-dgram: true

sideEffectsCache: false
