configDependencies:
  '@pnpm/plugin-trusted-deps': 0.2.1+sha512-eexZgdsCkalvvWOdtlhlLoMg5Kylqj7CjeAzhSshEi3Io3TJawdKNwRg10ObK0V4DSWNF0lP2ilobwUKUdoCyw==

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@azat-io/*'

onlyBuiltDependenciesFile: node_modules/.pnpm-config/@pnpm/plugin-trusted-deps/allow.json
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  netlify-cli: true
  sharp: true
  simple-git-hooks: true
  unix-dgram: true

sideEffectsCache: false
