<template>
  <svg viewBox="0 0 333 308">
    <rect
      x="7"
      y="48"
      width="101"
      height="12"
      rx="2"
      fill="var(--vp-c-brand)"
    />
    <rect x="7" y="8" width="101" height="12" rx="2" fill="var(--vp-c-brand)" />
    <rect
      x="225"
      y="8"
      width="101"
      height="12"
      rx="2"
      fill="var(--vp-c-brand)"
    />
    <rect
      x="7"
      y="68"
      width="101"
      height="12"
      rx="2"
      fill="var(--vp-c-brand)"
    />
    <rect
      x="117"
      y="68"
      width="39"
      height="12"
      rx="2"
      fill="var(--vp-c-text-3)"
    />
    <rect
      x="7"
      y="28"
      width="101"
      height="12"
      rx="2"
      fill="var(--vp-c-brand)"
    />
    <rect
      x="7"
      y="108"
      width="40"
      height="12"
      rx="2"
      fill="var(--vp-c-text-3)"
    />
    <rect
      x="37"
      y="128"
      width="58"
      height="12"
      rx="2"
      fill="var(--vp-c-brand)"
    />
    <rect
      x="66"
      y="208"
      width="100"
      height="12"
      rx="2"
      fill="var(--vp-c-text-3)"
    />
    <rect
      x="174"
      y="208"
      width="50"
      height="12"
      rx="2"
      fill="var(--vp-c-brand)"
    />
    <rect
      x="65"
      y="228"
      width="74"
      height="12"
      rx="2"
      fill="var(--vp-c-text-3)"
    />
    <rect
      x="147"
      y="228"
      width="40"
      height="12"
      rx="2"
      fill="var(--vp-c-brand)"
    />
    <rect
      x="66"
      y="168"
      width="42"
      height="12"
      rx="2"
      fill="var(--vp-c-text-3)"
    />
    <rect
      x="116"
      y="168"
      width="170"
      height="12"
      rx="2"
      fill="var(--vp-c-brand)"
    />
    <rect
      x="66"
      y="248"
      width="51"
      height="12"
      rx="2"
      fill="var(--vp-c-text-3)"
    />
    <rect
      x="125"
      y="248"
      width="25"
      height="12"
      rx="2"
      fill="var(--vp-c-brand)"
    />
    <rect
      x="66"
      y="188"
      width="94"
      height="12"
      rx="2"
      fill="var(--vp-c-text-3)"
    />
    <rect
      x="168"
      y="188"
      width="80"
      height="12"
      rx="2"
      fill="var(--vp-c-brand)"
    />
    <rect
      x="66"
      y="148"
      width="66"
      height="12"
      rx="2"
      fill="var(--vp-c-text-3)"
    />
    <rect
      x="66"
      y="268"
      width="42"
      height="12"
      rx="2"
      fill="var(--vp-c-text-3)"
    />
    <rect
      x="140"
      y="148"
      width="186"
      height="12"
      rx="2"
      fill="var(--vp-c-brand)"
    />
    <rect
      x="57"
      y="108"
      width="40"
      height="12"
      rx="2"
      fill="var(--vp-c-brand)"
    />
    <rect
      x="55"
      y="108"
      width="66"
      height="12"
      rx="2"
      fill="var(--vp-c-brand)"
    />
    <rect
      x="129"
      y="108"
      width="20"
      height="12"
      rx="2"
      fill="var(--vp-c-text-3)"
    />
    <rect
      x="7"
      y="288"
      width="20"
      height="12"
      rx="2"
      fill="var(--vp-c-text-3)"
    />
    <rect
      x="214"
      y="28"
      width="70"
      height="12"
      rx="2"
      fill="var(--vp-c-brand)"
    />
    <rect
      x="116"
      y="48"
      width="52"
      height="12"
      rx="2"
      fill="var(--vp-c-text-3)"
    />
    <rect
      x="176"
      y="48"
      width="52"
      height="12"
      rx="2"
      fill="var(--vp-c-brand)"
    />
    <rect
      x="116"
      y="28"
      width="90"
      height="12"
      rx="2"
      fill="var(--vp-c-text-3)"
    />
    <rect
      x="116"
      y="8"
      width="101"
      height="12"
      rx="2"
      fill="var(--vp-c-text-3)"
    />
  </svg>
</template>
