name: Install Tools

runs:
  using: composite
  steps:
    - name: Install Node
      uses: actions/setup-node@d7a11313b581b306c961b506cfc8971208bb03f6 # v4.4.0
      with:
        node-version: 24

    - name: Install pnpm
      uses: pnpm/action-setup@f2b2b233b538f500472c7274c7012f57857d8ce0 # v4.1.0
      with:
        version: 10
        run_install: false
