name: Docs

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443 api.netlify.com:443 github.com:443
            registry.npmjs.org:443 release-assets.githubusercontent.com:443
            telemetry.astro.build:443

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Install Tools
        uses: ./.github/actions/install-tools

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build Docs
        run: pnpm run docs:build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@d22a32a27c918fe470bbc562e984f80ec48c2668 # v4.0.0
        with:
          publish-dir: './dist'
          production-branch: main
          deploy-message: 'deploy from github actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
